language: csharp
solution: Database.sln
install:
 - nuget restore Database.sln
 - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
 - xbuild /p:Configuration=Release Database.sln
 - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./UnitTests/bin/Release/UnitTests.dll